name: CI

on:
  push:
    branches: [ phw-1 ]
  pull_request:
    branches: [ phw-1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: asdfassdf
        run: echo sdfsdf

      - name: start
        run: ./linters/run.sh
