name: CI

on:
  push:
    branches: [ phw-1 ]
  pull_request:
    branches: [ phw-1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Static code analysis
        shell: bash
        run: ./linters/run.sh

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      # - name: Valgring test
      #   working-directory: ${{github.workspace}}/build
      #   shell: bash
      #   run: |
          
